#!/bin/bash
# created by: Zell
#===============================================================================
# variables

#---------------------------------------
# source file

source /usr/local/sbin/stdlib

#---------------------------------------
# common values

LOGNAME=$PROG
LOG=/var/log/$LOGNAME.log
LOGROCONF=/etc/logrotate.d/$LOGNAME

#---------------------------------------
# initial values

SHOWALL=false

#===============================================================================
# help text

HELP_TXT="
This script runs:
  # cat ./.git/config
  # git branch -a --color
  # git show-ref |egrep -i 'master|$BRANCH'
  # git log --graph --all --decorate --abbrev-commit --oneline
  # git status

SYNTAX:
  # $PROG [OPTIONS]

OPTIONS:
  -h, --help         display this help text and exit
  -l, --log          enable logging to a file
  -v, --verbose      be verbose
  -vv, --debug       turn on debugging (very verbose)
  -dr, --dryrun      do a dry run
  -a, --show-all     don't cut off any output (noramlly, only 10 lines of each 'git' command are shown)

EXAMPLES:
  Normal operation:  # $PROG
  Dry run:           # $PROG -vv -dr
  Logging:           # $PROG -v --log

NOTES:
  don't combine options:
    correct:         # $PROG -l -vv
    incorrect:       # $PROG -lvv

"

#===============================================================================
# functions

#---------------------------------------
# 

#===============================================================================
# script start

#---------------------------------------
# process options

while (( "$#" > 0 )) ;do
  case $1 in
    -h|--help)      f_usage 0                               ;;
    -v|--verbose)   VERBOSE=true ;shift                     ;;
    -l|--log)       LOGGING=true ;shift                     ;;
    -vv|--debug)    VERBOSE=true ;DEBUG=true ;shift         ;;
    -dr|--dryrun)   VERBOSE=true ;DRYRUN=true ;shift        ;;
    -a|--show-all)  SHOWALL=true ;shift                     ;;
    "")             break                                   ;;
    *)              f_msg -e "Unkown option(s): $*" ;break  ;;
  esac
done
VERBOSE=true
LOGGING=false

f_msg -l -d "SCRIPT START"

#---------------------------------------
# arguments

f_msg -d "VERBOSE=$VERBOSE"
f_msg -d "LOGGING=$LOGGING"
f_msg -d "DEBUG=$DEBUG"
f_msg -d "DRYRUN=$DRYRUN"
f_msg -d "SHOWALL=$SHOWALL"

#---------------------------------------
# error checks

if [[ ! -d ./.git ]] ;then
  f_msg -e "Git has not been initialized here: `pwd`"
fi

#===============================================================================
# body

#---------------------------------------
# git branch, show-ref, & log

BRANCH=`git branch |awk '{print $2}'`

if [[ $SHOWALL == true ]] ;then
  f_msg "DISPLAY GIT CONFIG"
  f_run "cat ./.git/config"
  f_msg "DISPLAY GIT BRANCH"
  f_run "git branch -a --color"
  f_msg "DISPLAY SHOW-REF"
  f_run "git show-ref |egrep -i 'master|$BRANCH'"
  f_msg "DISPLAY GIT LOG"
  f_run "git log --graph --all --decorate --abbrev-commit --oneline |cat"
else
  f_msg "DISPLAY GIT CONFIG"
  f_run "cat ./.git/config"
  f_msg "DISPLAY GIT BRANCH (truncated)"
  f_run "git branch -a --color |head"
  f_msg "DISPLAY SHOW-REF (truncated)"
  f_run "git show-ref |egrep -i 'master|$BRANCH' |head"
  f_msg "DISPLAY GIT LOG (truncated)"
  f_run "git log --graph --all --decorate --abbrev-commit --oneline |head"
fi

#---------------------------------------
# git status

f_msg "DISPLAY GIT STATUS"
f_run "git status"

#===============================================================================
# cleanup

f_logro
f_exit
