#!/bin/bash
# created by: Zell
#===============================================================================
# variables

#---------------------------------------
# source file

source /usr/local/sbin/stdlib

#---------------------------------------
# common values

LOGNAME=$PROG
LOG=/var/log/$LOGNAME.log
LOGROCONF=/etc/logrotate.d/$LOGNAME
TMP=/tmp/ksshagent.$SSDATE

#===============================================================================
# help text

HELP_TXT="
This script searches for \"ssh-agent -s\" processes and kills them.

SYNTAX:
  # $PROG [OPTIONS]

OPTIONS:
  -h, --help         display this help text and exit
  -l, --log          enable logging to a file
  -v, --verbose      be verbose
  -vv, --debug       turn on debugging (very verbose)
  -dr, --dryrun      do a dry run

EXAMPLES:
  Normal operation:  # $PROG
  Dry run:           # $PROG -vv -dr
  Logging:           # $PROG -v --log

NOTES:
  don't combine options:
    correct:         # $PROG -l -vv
    incorrect:       # $PROG -lvv

"

#===============================================================================
# functions

#---------------------------------------
# display

f_display () {
DISPLAY=`ps -ef |grep 'ssh-agent -s' | grep $(whoami) |grep -v grep |head -n -6 |awk '{print $2}'`
f_msg "`date` Total 'ssh-agent -s' processes: `echo $DISPLAY |wc -l`"
}

#===============================================================================
# script start

#---------------------------------------
# process options

while (( "$#" > 0 )) ;do
  case $1 in
    -h|--help)     f_usage 0                               ;;
    -v|--verbose)  VERBOSE=true ;shift                     ;;
    -l|--log)      LOGGING=true ;shift                     ;;
    -vv|--debug)   VERBOSE=true ;DEBUG=true ;shift         ;;
    -dr|--dryrun)  VERBOSE=true ;DRYRUN=true ;shift        ;;
    "")            break                                   ;;
    *)             f_msg -e "Unkown option(s): $*" ;break  ;;
  esac
done
VERBOSE=true
LOGGING=false

f_msg -l -d "SCRIPT START"

#---------------------------------------
# arguments

f_msg -d "VERBOSE=$VERBOSE"
f_msg -d "LOGGING=$LOGGING"
f_msg -d "DEBUG=$DEBUG"
f_msg -d "DRYRUN=$DRYRUN"

#---------------------------------------
# error checks


#===============================================================================
# body

# display before
f_display

# kill ssh-agents
f_msg "creating ssh-agent pid list..."
for PID in `echo $DISPLAY` ;do
  f_msg "killing $PID..."
  f_run "kill -3 $PID"
  sleep .1
done

# display after
f_display

#===============================================================================
# cleanup

f_logro  # rotate log
f_exit
